In [1]:
from deepface import DeepFace
import tensorflow as tf

In [2]:
import cv2 as cv
import numpy as np

In [3]:
import os
print(os.getcwd())


C:\Users\Celsius\Documents\GitHub\DeepFaceAttendance


In [4]:
model = DeepFace.find(img_path='C:/Users/Celsius/Documents/GitHub/DeepFaceAttendance/test.jpeg', 
                       db_path='./Database', 
                       enforce_detection=False, 
                       model_name='VGG-Face')


24-09-25 17:21:25 - Searching C:/Users/Celsius/Documents/GitHub/DeepFaceAttendance/test.jpeg in 7 length datastore
24-09-25 17:21:30 - find function duration 4.768295526504517 seconds


In [5]:
model[0]['identity'][0].split('\\')[1]

'Elon'

In [6]:
model[0]['source_x'][0]

110

In [7]:
model[0]

identity  \
0  ./Database\Elon\.ipynb_checkpoints\elon-musk-r...   
1  ./Database\Elon\elon-musk-rt-jt-230511_1683834...   
2     ./Database\Elon\WSIRZRWN6BOMBA4VHAUGK32TVA.jpg   
3  ./Database\Elon\.ipynb_checkpoints\WSIRZRWN6BO...   

                                       hash  target_x  target_y  target_w  \
0  e21db918af282df474009aaa7fdbe4ba182029cf        66        76       376   
1  b17d3d6c563345cc20c178284d1b089c595113df        66        76       376   
2  e24c05686d5ba268f71042cdbd4b1160a656f236      1491       679      1772   
3  b6d42b9aebc66da08f524fb5aa48a890c1ae15a9      1491       679      1772   

   target_h  source_x  source_y  source_w  source_h  threshold  distance  
0       376       110        22        76        76       0.68  0.236281  
1       376       110        22        76        76       0.68  0.236281  
2      1772       110        22        76        76       0.68  0.258062  
3      1772       110        22        76        76       0.68  0.258062

In [8]:
# model = 'liveness.model'
# model = tf.keras.models.load_model(model)

In [9]:
cap = cv.VideoCapture(0)
while True:
    state, frame = cap.read()
    if state != True:
        break
    
    res = DeepFace.find(frame, db_path='./Database', enforce_detection=False, model_name='VGG-Face')

    if len(res[0]['identity']) > 0:
        name = res[0]['identity'][0].split('\\')[1]
        
        x_min = int(res[0]['source_x'][0])
        y_min = int(res[0]['source_y'][0])
        
        w = res[0]['source_w'][0]
        h = res[0]['source_h'][0]

        x_max = int(x_min + w)
        y_max = int(y_min + h)

        #liveness
        # img = frame[y_min:y_max, x_min:x_max]
        # img = cv.resize(img, (32, 32))
        # img = img.astype('float')/255.0 #normalize to 0 1
        # img = tf.keras.preprocessing.image.img_to_array(img) #img to array
        # img = np.expand_dims(img, axis=0) #expand the 1st dim with batch_size

        # liveness = model.predict(img)
        # liveness = liveness[0].argmax() #liveness out put [[fake, real]] take 1 much bigger to have the result
        
        

        cv.rectangle(frame, (x_min, y_min), (x_max, y_max), (0, 255, 0), 4)
        cv.rectangle(frame, (x_min, y_min-25), (x_max, y_min), (255,255,255), -1)
        cv.putText(frame, name, (x_min, y_min), cv.FONT_HERSHEY_SIMPLEX, 3, (255, 0, 0), 3, cv.LINE_AA)


        # cv.putText(frame, str(liveness), (x_min, y_max+25), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0), 2, cv2.LINE_AA)

    cv.imshow('Attendance', frame)
    
    c = cv.waitKey(1)
    if c == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

24-09-25 17:21:38 - Searching [[[  0  94  48]
  [  0  92  51]
  [ 21 107  77]
  ...
  [131 114  97]
  [129 105  79]
  [138 111  79]]

 [[  1  92  50]
  [  0  88  51]
  [ 23 105  77]
  ...
  [120 107  89]
  [126 107  79]
  [134 113  79]]

 [[  6  89  53]
  [  3  84  52]
  [ 30 105  81]
  ...
  [109 105  83]
  [121 112  81]
  [126 116  80]]

 ...

 [[170 178 185]
  [174 181 188]
  [175 181 187]
  ...
  [120 115  88]
  [115 110  84]
  [114 110  85]]

 [[166 174 182]
  [170 177 184]
  [173 179 186]
  ...
  [118 115  88]
  [115 114  87]
  [112 112  86]]

 [[170 177 186]
  [172 178 187]
  [173 179 186]
  ...
  [118 116  89]
  [115 115  88]
  [110 111  85]]] in 7 length datastore
24-09-25 17:21:39 - find function duration 0.8801236152648926 seconds
24-09-25 17:21:39 - Searching [[[ 85  86 107]
  [ 90  89 109]
  [ 93  90 105]
  ...
  [147 125  94]
  [150 129  92]
  [152 131  92]]

 [[ 84  90 107]
  [ 86  90 105]
  [ 99 100 112]
  ...
  [151 129  97]
  [150 129  91]
  [149 128  88]]

 [[ 80  95